#
###################################
# Site wide configuration
####################################
#
title: Reza Davari
email: davari.mreza@gmail.com
description: Reza's notes and projects.
url: https://davari.io
keywords: ["Mohammd Reza Davari", "Mohammad Reza","Reza","Reza Davari","Davari","Machine Learning","NLP","AI","Artificial Intelligence"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Montreal
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Reza Davari
  job: PhD Student @ <a href="https://mila.quebec/en/" target="_blank">Mila</a> and <a href="https://www.concordia.ca/ginacody.html" target="_blank">Concordia University</a>
  bio: "AI enthusiast, currently focused on NLP, CV, and CL. A watermelon connoisseur. Based in Montreal, QC."
  email: davari.mreza@gmail.com
  disqus-shortname: davari-io
  twitter: davari_reza #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-148531218-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rezazzr #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rezadavari #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
  googlescholar: 4AztFtEAAAAJ

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
